### ISSUE TITLE
[Database] [Risorse] Dubbi su cosa inserire

### ISSUE THREAD

**Issue by ali-ce** [ondata/taskforse.it#44]
Un utente ha compilato modulo per suggerire task force puntando a questo link : https://innovazione.gov.it/task-force-dati-le-relazioni-delle-attivita-dei-gruppi-che-hanno-valutato-le-app/

La task force dati ce l'abbiamo già, ma questo link segnalatoci lo terrei per aggiungerlo alle risorse associate alla task force. 

Volevo però prima avere conferme su queste due cose, che sono come procederei io:

-  Le relazioni delle attività delle task force vanno nello sheet risorse (ma penso di sì)
- Non catalogo come unica risorsa il link fornito ma entro nella pagina e creo record per ciascuna delle 4 relazione dei singoli gruppi. 
- La task force ha anche un intero [github repo](https://github.com/taskforce-covid-19/documents) con tutti i documenti pubblicati come frutto delle sue attività. Metto link al repo come risorsa in unico record (cosa più veloce + così si trovano info aggiornate.), oppure metto record per ogni singolo doc contenuto (un accollo + difficile stare dietro ad aggiornamenti...ma più corretto dal punto di vista DB)? Io andrei per includere solo github repo per ora e eventuali doc. specifici solo se segnalati da qualcuno.

**Comment by jenkin** [comment]
Dunque, secondo me le "relazioni" di un gruppo, con data e magari firma, hanno carattere ufficiale e per questo sono assimilabili ai "verbali", io metterei lì tutti quei pdf, uno a uno. Poi volendo possiamo chiamarli "Verbali e relazioni" invece che solo "Verbali".

Tutte le altre risorse (inclusi siti, repo github, ecc) li metterei in "risorse", una per ogni homepage.
