### ISSUE TITLE
Blocchi neri dove mancano info

### ISSUE THREAD

**Issue by ali-ce** [ondata/taskforse.it#46]
È normale che si veda questa cosa qui dove mancano informazioni? 
<img width="645" alt="Screenshot 2020-05-15 at 16 34 50" src="https://user-images.githubusercontent.com/7140368/82062354-45649000-96ca-11ea-981c-d8bfc1cdc110.png">

**Comment by jenkin** [comment]
S

**Comment by ali-ce** [comment]
Ah ok. in effetti ora che lo spieghi è bella matafora, sembra sì i redacted dei FOIA. La prima impressione a pelle però è stata che ci fosse errore, ma non saprei che fare di meglio.

**Comment by jenkin** [comment]
Aggiunto un tooltip con call to action...
