### ISSUE TITLE
[Design] [Task force page] Verbali e Risorse da sistemare un po' in vista di aumento contenuti.

### ISSUE THREAD

**Issue by ali-ce** [ondata/taskforse.it#47]
Le sezioni Verbali e Risorse in basso alla pagina secondo me diventano un po' diseprsive se iniziano ad esserci tanti contenuti, soprattutto se con titoli lunghi. Vedi pagina task force dati dove ho inserito 6 verbali: https://www.taskforse.it/task-forse/dati-innovazione

Alcuni possibili fix..(ma su questo penso sia @JpTapo la persona più adatta):

- Intanto omogenizzare i font , andrei per la size più piccola delle risorse(verbali sono size 1rem, risorse 0.875 rem)
- Forse rendere la width un po' più larga così i titoli un po' più lunghi non fanno "effetto malloppo"? 

I verbali sono solo 6...eppure l'effetto è da endless scroll :)

<img width="403" alt="Screenshot 2020-05-16 at 01 36 18" src="https://user-images.githubusercontent.com/7140368/82104067-b54c3800-9715-11ea-96b1-c846ce5eb9e4.png">

**Comment by jenkin** [comment]
Pienamente d'accordo, la differenza di font è un bug, ok per allargare le colonne.

Io metterei anche una semplice casella di ricerca che filtri la lista *as you type*, almeno nel caso in cui ci fossero più di 5 elementi.

**Comment by JpTapo** [comment]
@jenkin nell'ultimo mockup su slack lo trovi già con le colonne full screen come la parte della tabella dei membri :)
